[project]
name = "dvc-example"
version = "0.1.0"
description = ""
authors = [
    {name = "test_pp_3sem",email = "go130913@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dvc (>=3.59.1,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
